services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123
      POSTGRES_DB: strapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - strapi-net

  strapi:
    build: .
    container_name: strapi
    depends_on:
      - postgres
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi123
    ports:
      - "1337:1337"
    networks:
      - strapi-net


  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - strapi
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - strapi-net

networks:
  strapi-net:
    driver: bridge

volumes:
  postgres_data:
